version: "3.9"

# Use this if you push a prebuilt image to a registry and don't want to build on the Pi.
# Replace IMAGE below with your registry image (e.g., ghcr.io/you/wallet-health-agent:latest).
# Example build/push from repo root:
#   docker build -t ghcr.io/you/wallet-health-agent:latest .
#   docker push ghcr.io/you/wallet-health-agent:latest

services:
  wallet-agent:
    image: ghcr.io/your-namespace/wallet-health-agent:latest  # <-- CHANGE THIS
    container_name: wallet-agent
    restart: unless-stopped
    env_file:
      - ./.env.production
    environment:
      # Safe defaults; can be overridden in .env.production
      - MASUMI_BYPASS_PAYMENTS=false
      - RATE_LIMIT_RPM=60
      - LOG_LEVEL=INFO
      - CACHE_TTL_SEC=86400
      - IDEMPOTENCY_WINDOW_SEC=600
    volumes:
      - wallet_data:/app/data
      - wallet_reports:/app/reports
    networks:
      - web
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/availability"]
      interval: 30s
      timeout: 5s
      retries: 3

  caddy:
    image: caddy:2.7-alpine
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - wallet-agent
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_data:/data
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  wallet_data:
  wallet_reports:
  caddy_config:
  caddy_data:
